services:
  - type: web
    name: gp-maker
    runtime: python
    buildCommand: apt-get install -y libreoffice && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
